### ISSUE TITLE
Started, and what's next

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland-wiki#1]
The website is nearly ready now, and it feels great after days of work finally becomes fruit.

So, what's next?

# Finish for Migration
- [x] Status

@end-4 If you're satisfied, then it's time to eventually finish migration.

i.e. The built-in wiki and README of <https://github.com/end-4/dots-hyprland> are ready to be removed in favor of this one, and then the URL <https://end-4.github.io/dots-hyprland-wiki> should be added to suitable places.

# l10n (optional)
- [x] Status

The site supports multi language, but it needs manual translation first.
I guess it will be fast if use AI to translate and then manually check and modify.

> Of course, a person is capable to do translation only when the target language is their native language, or they are really experienced on this language.

# Write Dev notes (optional)
- [x] Status

@end-4 The part of [Dev notes](https://end-4.github.io/dots-hyprland-wiki/en/i-i/05dev/) is far from complete.
You may write needed content when you have time.

# WS over 10 (optional)
- [x] Status

The [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) does not contains "WS over 10" things currently.
@midn8hustlr Since you're the main contributor for this workflow, I sincerely invite you to write this part and submit a PR, if you'd like to.
Thanks in advance!

---

That's it for now.
Happy Chinese New Year!

**Comment by end-4** [comment]
wonderful! 
## The wiki
- I like it, but I'll just have material colors like my rice

## Translation
- Let's not use automated translation. I don't want weird, low-quality stuff
- I can do Vietnamese. And I assume you're doing Chinese?

## Dev notes
- I like the idea. I'll do it

~~overview for workspace 11+ is broken btw~~

**Comment by clsty** [comment]
> I like it, but I'll just have material colors like my rice

Sure, feel free to edit the themes. The theme originally comes from [the wiki site](https://clsty.github.io/arCNiso) of my project, I just copied them here.

> Let's not use automated translation. I don't want weird, low-quality stuff

I actually meant "assisted", not "automated". If a person speaks the target language every day, then I think it's ok if the person read the whole result and modified every parts that's not suitable, until the person feels nothing wrong.

> I can do Vietnamese. And I assume you're doing Chinese?

Yes, you're right.

> overview for workspace 11+ is broken btw

Hmmm... it seems worky for my PC, but maybe I just don't know what is "worky" at first place lol

**Comment by clsty** [comment]
@end-4 I suggest we close the built-in "Wiki" for this repo in repo settings.

Also please open "Discussions" for this repo, since the "Issues" may not be suitable for some topic.

**Comment by end-4** [comment]
> I suggest we close the built-in "Wiki" for this repo in repo settings.

and that's how i discovered you could allow others to edit wiki lmao
![image](https://github.com/end-4/dots-hyprland-wiki/assets/97237370/e0f148c6-6c96-4ecd-8801-fc26cb83cd0a)


- Discussions are already enabled

**Comment by clsty** [comment]
> and that's how i discovered you could allow others to edit wiki lmao

Welp, I knew it before, but there will be no limit for editing at all so that it may risk spams.

**Comment by midn8hustlr** [comment]
Fabulous work @clsty 

> The [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) does not contains "WS over 10" things currently. @midn8hustlr Since you're the main contributor for this workflow, I sincerely invite you to write this part and submit a PR, if you'd like to. Thanks in advance!

I will be happy to contribute.
Happy Chinese New Year!

**Comment by clsty** [comment]
> Discussions are already enabled

@end-4 I actually meant the discussion for this repo (wiki).

I just wanted to create a discussion and find it's not enabled here...

P.S. I'm confused with "Why why why why" in `index.mdx`. Is this really a good sentence?

**Comment by clsty** [comment]
> Discussions are already enabled

@end-4 I actually meant the discussion for this repo (wiki).

I just wanted to create a discussion and find it's not enabled here...

P.S. I'm confused with "Why why why why" in `index.mdx`. Is this really a good sentence?

**Comment by end-4** [comment]
> I actually meant the discussion for this repo (wiki).

oh okay

> I'm confused with "Why why why why" in index.mdx. Is this really a good sentence?

I wanted a text that's short enough so they look good with the cards. And that "why"×4 is something unusual that makes people scroll down to read

> Group label on sidebar now supports i18n. You may want to add translation for vi in astro.config.mjs.

Cool, I've found some awkwardly translated UI elements and will fix them

**Comment by end-4** [comment]
can we translate anything other than the content and sidebar?

**Comment by clsty** [comment]
> can we translate anything other than the content and sidebar?

I guess so, refer to <https://starlight.astro.build/guides/i18n/#translate-starlights-ui>, unsure about whether this is what you want though.

**Comment by end-4** [comment]
i agree

**Comment by clsty** [comment]
@midn8hustlr This issue is 3/4 done.

I'm looking forward to your contribution on WS-over-11 workflow, and it will be the last piece to make if complete :)

**Comment by midn8hustlr** [comment]
Sorry I didn't have my laptop past week, will try to update today

**Comment by clsty** [comment]
> you shouldn't update yet
> i **still haven't fixed** that workflow for workspace 11+ since when I implemented animations into it

Oops, sorry I didn't understand the situation clearly @midn8hustlr @end-4 

Please take your time.

**Comment by end-4** [comment]
@midn8hustlr I'm happy to say that group behavior of the overview widget has now been fixed in https://github.com/end-4/dots-hyprland/commit/b4fe73c060e488e7c50423f4a9bf444361710062
you can update now

**Comment by zer0-sh** [comment]
> I've moved the dev notes into a new group.
> 
> I think it's actually not necessary to translate the dev notes, because:
> 
>     * A dev must be familiar with English.
> 
>     * The dev notes may update much more often than other docs, so that translation update for it may cost too much time, or not up-to-date often, which makes the translated dev notes meaningless.
> 
>     * I have the dev notes collapsed by default on sidebar. And, even if a person using non-English language clicks on it, it won't return `404`, but just fallback to the English doc.
> 
> 
> @end-4 If you agree with me, I'll remove the translated dev notes, only keep the English ones. They don't contain many words in total, so it's not a big loss, and this act will surely save us lots of time in future.

I’m working on the Spanish translation. I started with the Dev section and left doc-site-contrib for last.

And I came across the note that brought me to this issue.

In Spanish, we use the expression "Quedé como payaso," which refers to looking ridiculous or silly in front of everyone HAHAHAHAHAHAHA, and that’s literally how I ended up.
