### ISSUE TITLE
[Feature] Need Some document for AGS change key bind

### ISSUE THREAD

**Issue by singer233** [end-4/dots-hyprland-wiki#5]
**What would you like to be added?**
Some document on how to customization key bind for the AGS
I have read the AGS wiki and seems like changing key bind for AGS is not as easy as Hyprland
**How will it help**
Some one (like me) may want to change key bind for the AGS

**Comment by clsty** [comment]
The global keybindings are defined in `.config/hypr/hyprland/keybinds.conf`.

For local keybindings on AGS widgets/bars, yes, it's much more difficult than Hyprland.
E.g. For this [issue](https://github.com/end-4/dots-hyprland/issues/255).

But, I guess we could at least give some directions or hints about this in Dev Notes. What do you think? @end-4

**Comment by end-4** [comment]
If you meant keybinds like Ctrl+P to pin and Ctrl+Tab to switch tabs on the left sidebar then those are currently hard-coded
- For now, look in the widget whose keybinds you want to change and find `.on('key-press-event'`. 
  - Use some common sense to change stuff there... Hints:
    - `Gdk.KEY_p` means the P key. 
    - `event.get_state()[1] & Gdk.ModifierType.CONTROL_MASK` is true when Ctrl is held. There are more masks and you can search for them...

I might have this configurable later when I implement some way to offer easy configuration

---

@clsty 
> But, I guess we could at least give some limited directions or hints about this in Dev Notes. What do you think? @end-4

Idk... I guess that would belong to a "to-do" category if I add it. It's a problem that I should address and not force people to read the source

**Comment by end-4** [comment]
added keybinds
I'm not sure if all the masks work, and you gotta read gdk docs page to know the keys, but it works
